POST http://localhost:10000/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFETUlOIiwiaWQiOiI2NTU0ZTc1M2M0YjBiMWFjYWMzYzVjNGQiLCJpYXQiOjE3MDAwNjMwODh9.eKPq3Ci5vGXQpDy2E0UWvMMGUh2aPXpXf34Jj04IFP4

{
  "content": "Wassup dawg! This is the administrator!",
  "important": "true",
  "userId": "6554e753c4b0b1acac3c5c4d"
}