POST http://localhost:10000/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ilplcm9vb19jb29vTCIsImlkIjoiNjU1MmI0YTA0ZTBmZTg0YmVjMTA2OWY1IiwiaWF0IjoxNjk5OTkxMDUxfQ.0i69E-k5Ic4l8-sYaRQpJpLdaZOLfT69T_7Rjl7FQS8

{
  "content": "HERE @ the bucks",
  "important": "true",
  "userId": "6552b4a04e0fe84bec1069f5"
}