POST http://localhost:10000/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFETUlOIiwiaWQiOiI2NTU0ZTc1M2M0YjBiMWFjYWMzYzVjNGQiLCJpYXQiOjE3MDA1ODE0OTh9.9-1XNrWsrXiC4Z7Ei30XERrIZfxxjyzsJOF7a1-OGYU

{
  "content": "Wassup dawg! This is the administrator!",
  "important": "true",
  "userId": "6554e753c4b0b1acac3c5c4d"
}